### ISSUE TITLE
Slow CTC beam search decoder

### ISSUE THREAD

**Issue by vsl9** [NVIDIA/OpenSeq2Seq#228]
Current CTC beam search decoder runs on single CPU core. So it might be a bottleneck for speech recognition inference.

**Comment by bill-kalog** [comment]
I recently tried (with openseq2seq) the new decoder from mozilla-deepspeech which is based on this code https://github.com/parlance/ctcdecode/ . It can run on multiple cpus by default, if you feed batches of audio files, for trancriptions and the results I get are constantly better compared to the old decoder (without doing any hyperparameter tuning for alpa and beta, I just used the default values mozilla uses)

**Comment by ngochuyenluu** [comment]
@bill-kalog : Hi, I'm interested in your approach, could you please explain more about it? How you can use this ctcdecode combine with OpenSeq2Seq because I think the ctc-decode in OpenSeq2Seq is already built for their models. Which flags or hyperparameters have you replaced to use this ctc-decode?

**Comment by vsl9** [comment]
@ngochuyenluu, we already integrated Baidu beam search decoder in OpenSeq2Seq. That is the same decoder as in `ctcdecode` project. Please see https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition.html#decoders for more details.

**Comment by ArtemisZGL** [comment]
@vsl9 hello, can i use the baidu ctc decoder in training? and i also found that the baidu WarpCTC suppports gpu too, can we use it in this openSeq2Seq project?
